delete client_secret_file.json + settings upd
profcomff/timetable-backend pull request #11
Opened 2022-08-17 16:57 UTC by mixx3

2022-08-17 16:59 UTC, semen603089 requested changes

2022-08-17 16:59 UTC, semen603089 commented on .env.example
> +GROUPS=[]
удали пж Groups

2022-08-17 16:59 UTC, semen603089 commented on .env.example
> +GROUPS=[]
они не нужны больше

2022-08-17 19:21 UTC, mixx3 commented on .env.example
> +GROUPS=[]
кк

2022-08-18 17:49 UTC, dyakovri requested changes

2022-08-18 17:49 UTC, dyakovri commented on .env.example
> +CLIENT_SECRET={}
Давай назовем его GOOGLE_CLIENT_SECRET, чтоб было понятно что это такое

2022-08-18 17:49 UTC, dyakovri commented on calendar_backend/settings.py
> +    CLIENT_SECRET: Json
По умолчанию `{}`
Приложение же запустится с таким значением? Не упадет целиком?

2022-08-18 17:51 UTC, dyakovri commented
https://github.com/profcomff/timetable-backend/blob/main/.github/workflows/build_and_publish.yml#L74

Следующей строкой добавь `--env GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \`

2022-08-19 14:29 UTC, dyakovri commented on requirements.txt
> +asyncio
Он стандартный, нет смысла его сюда писать

2022-08-19 14:29 UTC, dyakovri commented on requirements.txt
> +starlette
На нем построен fastapi, он обязательно прилетит сам, кажется тут не нужен

2022-08-19 14:29 UTC, dyakovri commented on requirements.txt
> +fastapi~=0.75.2
Мне не нравится обозначение `~=`. Давай либо `>=`, либо вообще без него

2022-08-20 03:41 UTC, mixx3 commented on calendar_backend/settings.py
> +    CLIENT_SECRET: Json
Сделал, чтобы при пустом GOOGLE_CLIENT_SECRET выдавал 401 exception

2022-08-21 14:29 UTC, dyakovri commented on calendar_backend/settings.py
> +    CLIENT_SECRET: Json
Лучше 500тить 
Это же ошибка сервера, не клиента

2022-08-21 14:43 UTC, dyakovri approved these changes

2022-08-21 14:43 UTC, dyakovri approved these changes

2022-08-21 14:44 UTC, semen603089 approved these changes

2022-08-21 14:44 UTC, merged