Added getters, bd connection, etc
profcomff/timetable-backend pull request #2
Opened 2022-04-03 16:36 UTC by semen603089

2022-04-05 17:27 UTC, dyakovri requested changes

2022-04-05 17:27 UTC, dyakovri commented on calendar_backend/connect.py
> +    return keyring.get_password(system, username)
Для серверного ПО не надо использовать keyring
Во-первых, для него нет бэкэнда
Во-вторых некому будет заполнять этот пароль))
Зато для серверного ПО можно использовать переменные окружения и не бояться за их сохранность

2022-04-05 17:27 UTC, dyakovri commented on calendar_backend/app.py
> +engine = connect.engine
В данном случае я бы воспользовался кодом как модулем (`from connect import timetable, engine`)

2022-04-05 17:27 UTC, mrerro commented on calendar_backend/connect.py
> +DB_PORT = '25432'
Пароль так же как и данные о БД нужно хранить в переменных окружения файл `.env`. Для примера можно посмотреть https://github.com/profcomff/report-api/blob/main/report_api/settings.py `DB_DSN`

2022-04-06 14:21 UTC, semen603089 commented on calendar_backend/connect.py
> +DB_PORT = '25432'
Переделал на .env

2022-04-06 17:27 UTC, semen603089 commented on calendar_backend/connect.py
> +engine = create_engine(f"postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}", echo=True)
Не работает пока что автоматическое чтение из переменных окружения, так что пока что DB_DSN: PostgresDsn = os.getenv("DB_DSN")

2022-04-06 17:30 UTC, semen603089 commented on calendar_backend/app.py
> +exec(open("connect.py").read())
Сделал через вызов функции

2022-04-06 17:37 UTC, semen603089 commented on calendar_backend/connect.py
> +DB_PORT = '25432'
Переделал, но пока что автоматическое чтение из переменных окружения, так что пока что DB_DSN: PostgresDsn = os.getenv("DB_DSN")

2022-04-06 17:37 UTC, semen603089 commented on calendar_backend/connect.py
> +DB_PORT = '25432'
Выдает ошибку при автоматическом чтении
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
DB_DSN
field required (type=value_error.missing)

2022-04-11 22:26 UTC, dyakovri commented on calendar_backend/connect.py
> +class Settings(BaseModel):
Зачем тебе тут отдельный `class Settings`, если в settings.py уже есть такой класс?

2022-04-11 22:26 UTC, dyakovri commented on calendar_backend/connect.py
> +class Settings(BaseModel):
Наверное поэтому и не работает, что настройки уже прочитались

2022-04-11 22:26 UTC, dyakovri commented on calendar_backend/connect.py
> +timetable, engine = connect('timetable')
Тут не будет проблем с путем к таблице? Давай вынесем ее в переменную

2022-04-11 22:26 UTC, dyakovri commented on calendar_backend/app.py
> +async def get_timetable_by_teacher(teacher_name: str = Query(..., description="Teacher name")):
Пробовал запускать? Нормально работает с русскими ФИО?

2022-04-11 22:26 UTC, dyakovri commented on calendar_backend/app.py
> +async def get_timetable_by_place(audience_num: str = Query(..., description="Audience number")):
Пробовал запускать? Нормально работает с аудиториями, где есть дефисы и другие знаки?

2022-04-11 22:27 UTC, dyakovri commented
И удали файлик `.DS_Store` из PRа

2022-04-12 12:21 UTC, semen603089 commented on calendar_backend/app.py
> +async def get_timetable_by_place(audience_num: str = Query(..., description="Audience number")):
Да, только что проверил еще раз на: 5-19, Ауд. им. Хохлова, СФА, Л.каб.

2022-04-12 12:23 UTC, semen603089 commented on calendar_backend/app.py
> +async def get_timetable_by_teacher(teacher_name: str = Query(..., description="Teacher name")):
Да, перепроверил сейчас на:  Панкратов Н. Ю. и  Володин Б. А.
Стоит отметить, что в бд эти строки с пробелом в начале. А некоторые, например,   Марчук О. Н. с двумя пробелами

2022-04-12 13:35 UTC, dyakovri commented on calendar_backend/app.py
> +async def get_timetable_by_place(audience_num: str = Query(..., description="Audience number")):
Ужас какой, конечно, запрашиваем....

2022-04-12 13:59 UTC, semen603089 commented on calendar_backend/connect.py
> +class Settings(BaseModel):
Да, не заметил

2022-04-12 14:14 UTC, semen603089 commented on calendar_backend/app.py
> +async def get_timetable_by_place(audience_num: str = Query(..., description="Audience number")):
Ну а что делать :))

2022-04-12 19:30 UTC, dyakovri approved these changes

2022-04-12 21:01 UTC, merged