fix #40
profcomff/timetable-backend pull request #42
Opened 2022-08-27 21:19 UTC by semen603089

2022-08-28 00:20 UTC, semen603089 commented
22/22 tests

2022-08-28 04:47 UTC, semen603089 commented
тесты пофиксил, ручки добавил, details в одном месте выпилил(во втором он хотя бы не такой огромный) там лее ии excludes починился

2022-08-28 04:48 UTC, semen603089 commented
хотя нашел новый баг, но на тесты он нее влияет 
см issues 
пофикшу сегодня

2022-08-28 04:48 UTC, semen603089 commented
а это уже можно ревьюить

2022-08-28 04:49 UTC, semen603089 commented
limit=0 тоже пофиксил

2022-08-28 10:24 UTC, dyakovri requested changes

2022-08-28 10:24 UTC, dyakovri commented on calendar_backend/routes/event.py
> +from calendar_backend.models import CommentEvent as DbCommentEvent
Ты мог заметить, что я специально называл модельки БД просто, а схемы алхимии с постфиксами Get/Post/Patch
Так делают :) Как раз чтобы их друг от друга отличать и не писать AS

2022-08-28 10:24 UTC, dyakovri commented on calendar_backend/routes/event.py
> +from calendar_backend.models import CommentEvent as DbCommentEvent
Это скорее просто комментарий, чем требование изменить

2022-08-28 10:24 UTC, dyakovri commented on calendar_backend/routes/group.py
> +    return GroupGet.from_orm(Group.update(id, **group_inp.dict(exclude_unset=True), session=db.session))
А эти from orm точно нужны? Вроде и без них норм работает)) 
Они, вроде, неявно вызываются

2022-08-28 10:24 UTC, dyakovri commented on calendar_backend/routes/group.py
> +    return GroupGet.from_orm(Group.update(id, **group_inp.dict(exclude_unset=True), session=db.session))
Тоже правок не требует

2022-08-28 10:24 UTC, dyakovri commented on calendar_backend/routes/lecturer.py
> +    lecturer.total = len(lecturer.links)
Тут, кажется, лимиты и оффсеты работать не будут

2022-08-28 10:24 UTC, dyakovri commented on calendar_backend/routes/lecturer.py
> +    lecturer.total = len(lecturer.links)
И немного странно присваивать лектору тотал 
Я бы тут просто возвращал
{
Limit
Offset
Total
Items: [] 
}

2022-08-28 10:24 UTC, dyakovri commented on calendar_backend/routes/models/__init__.py
> +    LecturerComments
Почему они имеют разную структуру имени?😂

2022-08-28 10:24 UTC, dyakovri commented on calendar_backend/routes/models/lecturer.py
>      links: list[str]
Наверное, всё-таки items
Чтоб как везде

2022-08-28 10:24 UTC, dyakovri commented on tests/conftest.py
> +    RESOURCE_2 = f"timetable/lecturer/{id_}/photo"
Нигде не используется

2022-08-28 10:24 UTC, dyakovri commented on tests/lecturer/photos.py
>      assert response.ok, response.json()
Я этот тест не понял. Ты удаляешь не конкретную фотку? Фикстура, как будто, возвращает просто список фоток

2022-08-28 10:24 UTC, dyakovri commented on tests/conftest.py
> +    RESOURCE_2 = f"timetable/lecturer/{id_}/photo"
Почему ты id фотки присваиваешь лектору?

2022-08-29 16:36 UTC, dyakovri requested changes

2022-08-29 16:36 UTC, dyakovri commented on calendar_backend/routes/lecturer.py
> +        "total": len([row.link for row in lecturer.photos])
Дважды делаешь одно и то же +не смотришь на лимит?

2022-08-29 16:36 UTC, dyakovri commented on calendar_backend/routes/lecturer.py
> +        raise HTTPException(status_code=404, detail=f"Comment id:{id} not found in lecturer:{lecturer_id} comments list")
Странная проверка
Во первых после применения, а во вторых что вообще в comment post делает lecturer id?

2022-08-29 16:36 UTC, dyakovri commented on calendar_backend/routes/lecturer.py
> +        raise HTTPException(status_code=404, detail=f"Comment id:{id} not found in lecturer:{lecturer_id} comments list")
См выше

2022-08-29 16:36 UTC, dyakovri commented on calendar_backend/routes/lecturer.py
> +        raise HTTPException(status_code=404, detail=f"Comment id:{id} not found in lecturer:{lecturer_id} comments list")
См выше

2022-08-29 22:28 UTC, dyakovri reviewed
Там ещё один комментарий остался

2022-08-29 22:31 UTC, dyakovri approved these changes

2022-08-29 22:33 UTC, merged