Ревью комментариев и фоток
profcomff/timetable-backend pull request #49
Opened 2022-09-07 15:16 UTC by semen603089

2022-09-07 23:38 UTC, dyakovri requested changes
Я не увидел, что ты спрятал неотревьюеное из relationship и из get_all
Если второе мб у тебя не используется, то первое точно надо проверять

2022-09-07 23:38 UTC, dyakovri commented on calendar_backend/exceptions.py
> -        super().__init__(f"Objet {type.__name__} {id=} not found")
А чо ты равно убрал? Красиво же было `id=14` на выходе, и все понятно

2022-09-07 23:38 UTC, dyakovri commented on calendar_backend/exceptions.py
> +        super().__init__(f"Forbidden action with {type.__name__}, id={id}")
Можно же просто `{id=}`

2022-09-10 09:46 UTC, dyakovri requested changes

2022-09-10 09:46 UTC, dyakovri commented on calendar_backend/routes/event.py
> +review_event_router = APIRouter(prefix="/timetable/event/{event_id}", tags=["Review"])
Я бы мб подключил его внутрь event router
Хотя мб это и лишнее

2022-09-10 09:46 UTC, dyakovri commented on calendar_backend/routes/event.py
> +        raise ForbiddenAction(DbCommentEvent, id)
А разве они сюда вообще дойдут, записи с `approve_status=None`?

2022-09-10 09:46 UTC, dyakovri commented on calendar_backend/routes/event.py
> +    if not comment.event_id == event_id or comment.approve_status != ApproveStatuses.APPROVED:
Кажется, аппрув можно добавить в `Model.get`. Или создать подкласс типа `ReviewableModel` и в ней переопределить этот метод get
Чтобы не писать сто раз это `== апрув`, `!= апрув`

2022-09-10 09:46 UTC, dyakovri commented on calendar_backend/routes/event.py
> +        raise ForbiddenAction(DbCommentEvent, id)
Кажется, что пользователь просто должен получать 404, потому что непроревьюированный объект просто не будет виден

2022-09-10 09:46 UTC, dyakovri commented on calendar_backend/routes/models/base.py
> +    event_id: int
Ойой
Это нигде не аукнется? Никто их не использует?

2022-09-10 09:46 UTC, dyakovri commented on migrations/versions/c1e096cd1a66_add_review.py
> +    op.add_column('photo', sa.Column('approve_status', sa.Enum('APPROVED', 'DECLINED', name='approvestatuses', native_enum=False), nullable=True))
В базу Null точно нормально записывается
Я помню, у нас с тобой уже были из-за этого проблемы
Если все ок, то оставляй. Если есть проблемы, делай nullable=False и новый статус PENDING

2022-09-10 09:46 UTC, dyakovri commented on calendar_backend/routes/lecturer.py
> +    return Photo.from_orm(photo)
Возможно, комменты пора уносить в отдельный файл
А ревью в третий
Но это не горит

2022-09-10 09:46 UTC, dyakovri commented on tests/conftest.py
> +def comment_path_no_review(client_auth: TestClient, dbsession: Session, lecturer_path: str):
Conftest можно создавать в любой директории для тестов. Они будут видны только в текущей директории и ее поддиректориях. А фикстуры вообще можно определять в любых файлах, в том числе в файлах с тестами. Когда фикстура используется в одном файле, лучше там ее и определить.

Почему тут 2 разные фикстуры? Может стоит создать 1 фикстуру и добавить патч на ее статус прямо в тест?

2022-09-10 09:51 UTC, semen603089 commented on calendar_backend/routes/event.py
> +review_event_router = APIRouter(prefix="/timetable/event/{event_id}", tags=["Review"])
там тогда теги нормально не расставить 
он дублирует типа их в сваггере ;(

2022-09-10 09:52 UTC, semen603089 commented on calendar_backend/routes/event.py
> +        raise ForbiddenAction(DbCommentEvent, id)
ну чисто теоретически можно узнать id созданного коммента же
он не проревьюирорван
и бахнуть на него патч

2022-09-10 09:53 UTC, semen603089 commented on calendar_backend/routes/event.py
> +        raise ForbiddenAction(DbCommentEvent, id)
comment event возвращает id же
так что вполне можно сделать вызвать этот метод для непроревьюированного коммента

2022-09-10 09:54 UTC, semen603089 commented on calendar_backend/routes/event.py
> +        raise ForbiddenAction(DbCommentEvent, id)
exception_handler могу написать и кидать forbidden на эту ошибку

2022-09-10 09:55 UTC, semen603089 commented on calendar_backend/routes/models/base.py
> +    event_id: int
тесты живые
ты ж переименовал в БД там 
а тут вот не переименовано было

2022-09-10 10:00 UTC, dyakovri commented on calendar_backend/routes/event.py
> +        raise ForbiddenAction(DbCommentEvent, id)
Это же, вроде, схема json'а 
Там Илья может получать эти айдишки по названию lesson_id вместо event_id
Уточни сначала у него

2022-09-10 10:01 UTC, dyakovri commented on calendar_backend/routes/models/base.py
> +    event_id: int
Это же, вроде, схема json'а 
Там Илья может получать эти айдишки по названию lesson_id вместо event_id
Уточни сначала у него

2022-09-10 12:39 UTC, semen603089 commented on migrations/versions/c1e096cd1a66_add_review.py
> +    op.add_column('photo', sa.Column('approve_status', sa.Enum('APPROVED', 'DECLINED', name='approvestatuses', native_enum=False), nullable=True))
все ок пишется

2022-09-10 12:39 UTC, semen603089 commented on calendar_backend/routes/models/base.py
> +    event_id: int
илья еще не использовал эту модельку

2022-09-12 07:37 UTC, semen603089 commented on calendar_backend/routes/event.py
> +    if not comment.event_id == event_id or comment.approve_status != ApproveStatuses.APPROVED:
сделал only_approved

2022-09-13 13:14 UTC, dyakovri approved these changes

2022-09-13 13:14 UTC, dyakovri commented on calendar_backend/routes/lecturer.py
> +            else ApproveStatuses.PENDING,
Я бы этот if/else вытащил наружу

2022-09-13 17:10 UTC, merged