Push calendar to api
profcomff/timetable-backend pull request #5
Opened 2022-04-26 20:38 UTC by mixx3

2022-04-27 16:11 UTC, semen603089 requested changes
Ещё я бы может все это в асинхронных функциях сделал. У нас сейчас большая часть функционала на них работает

2022-04-27 16:11 UTC, semen603089 commented on calendar_backend/service.py
> +    credentials = google.oauth2.credentials.Credentials.from_authorized_user_info(json.loads(user_data.token), SCOPES)
А если user_data пустая? Например, ошибка была на сервере и такого Id нет

2022-05-27 17:53 UTC, dyakovri requested changes
Я не смотрел на логику работы и не запускал код, но по ощущениям:
1. Он не запустится 
2. Он даже не соберется в контейнер
3. Тут очень много хардкода
4. Тут есть места, где пользователю будет отдана какая-то конкретная штука вместо запрошенной им

2022-05-27 17:53 UTC, dyakovri commented on .gitignore
> +calendar_backend/.env
Верните файл обратно, он должен лежать в корне проекта. Если у вас в корне проекта не видно этот файл – у вас неправильно настроен запуск проекта

2022-05-27 17:53 UTC, dyakovri commented on .gitignore
> +.idea/
Игнорировать файлы вашей IDE стоит в личном глобальном гитигноре
Создайте файл, например, `C:/.gitignore_global`, добавьте в него `.idea/`, сохраните и выполните команду
```
git config --global core.excludesfile C:/.gitignore_global
```

2022-05-27 17:53 UTC, dyakovri commented on .gitignore
> +/calendar_backend/timetable_token.json
Файл токенов тоже лучше двинуть в корень репозитория

2022-05-27 17:53 UTC, dyakovri commented on Dockerfile
> +RUN pip install -r /app/requirements.txt
Запускать пробовали? Работает?

2022-05-27 17:53 UTC, dyakovri commented on alembic.ini
> +script_location = migrations
Не вижу эту папку в дереве каталогов. Скрипт без нее сломается.

2022-05-27 17:53 UTC, dyakovri commented on Dockerfile
> +COPY ./migrations /app/migrations
Не вижу эту папку в дереве каталогов. Скрипт без нее сломается.

2022-05-27 17:53 UTC, dyakovri commented on alembic.ini
> +sqlalchemy.url = postgresql://db.dyakov.space:15432/dev
Адреса базы лучше не хранить в скрипке и хранить в .env файле

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/app.py
>  from settings import Settings
Точно все эти импорты нужны?

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/app.py
> +templates = Jinja2Templates(directory="/Users/new/PycharmProjects/timetable-backend-2/templates")
Что-то мне кажется, что в докере не сработает этот путь

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/app.py
> +    redirect_uri='http://localhost:8000/credentials'
Какой локалхост в продакшене?

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/app.py
> +        redirect_uri='http://localhost:8000/credentials'
Какой локалхост в продакшене? [2]

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/db_event_create.py
> +    print(f"The error '{e}' occurred")
Зачем этот обработчик?

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/list_calendar.py
> +    service = get_calendar_service(44)
Что за 44?

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/service.py
> +    print(get_calendar_service(44))
42 – ответ на главный вопрос жизни, вселенной и всего такого. Но что за константа `44` тут?

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/settings.py
> +    TIMETABLE_NAME: str = 'timetable'
Да, оно же из .env файла само прилетает

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/timetable_account.py
> +
Этот кусок кода я уже видел. Повторяться нехорошо

2022-05-27 17:53 UTC, dyakovri commented on calendar_backend/timetable_account.py
> +                                                     'mmikee00800@gmail.com'))"""
Наверное не стоит оставлять код для отладки в мастер-ветке. А если надо – то стоит приложить к нему комментарий

2022-05-27 17:53 UTC, dyakovri commented on templates/calendar created.html
> +    ого работает чекни почту
https://to.dyakov.space/0ce3a25e7d94

2022-07-16 15:05 UTC, mixx3 commented on calendar_backend/service.py
> +    credentials = google.oauth2.credentials.Credentials.from_authorized_user_info(json.loads(user_data.token), SCOPES)
можно сделать вместо one() one_or_none() и обработать эти случаи, но без сервиса всё равно остальной код не будет работать. Ошибки с бд обрабатываются. `app.py` (кстати там нужно дописать обработку ошибок со стороны гугл сервера)

2022-07-16 15:06 UTC, mixx3 commented on .gitignore
> +.idea/
Не знал, что так можно) всё добавил

2022-07-17 09:41 UTC, semen603089 commented on calendar_backend/service.py
> +    credentials = google.oauth2.credentials.Credentials.from_authorized_user_info(json.loads(user_data.token), SCOPES)
Я обычно делаю one_or_none() и обрабатываю случай None. Это лучше чем общая ошибка(можно же написать свои exceptions и знать когда что выкидывается)

2022-07-18 17:04 UTC, semen603089 reviewed
не уверен конечно во всем, но может роме немного поможет

2022-07-18 17:04 UTC, semen603089 commented on calendar_backend/google_calendar_test.py
> +    test_can_create_empty_calendar()
посмотри pytest или unittest. лучше первое оно уже распространяется в нашей команде для тестов ахах)) и тесты лучше в отдельную папку

2022-07-18 17:04 UTC, semen603089 commented on calendar_backend/group_list.py
> +from db import Timetable
ничего не понял но ладно

2022-07-18 17:04 UTC, semen603089 commented on calendar_backend/timetable_account.py
> +        print('не нашел бля')
))

2022-07-18 18:03 UTC, dyakovri requested changes

2022-07-18 18:03 UTC, dyakovri commented on calendar_backend/timetable_account.py
> +        if os.path.exists('../timetable_token.json'):
Может пути к файлам все вынесем в `.env`?

2022-07-18 18:03 UTC, dyakovri commented on calendar_backend/timetable_account.py
> +        print('нашел, вссё окей')
Давай не писать в консоль через print)) 
Дебаг логи лучше использовать через `logging.debug()`

2022-07-18 18:03 UTC, dyakovri commented on requirements.txt
> +icalendar==4.1.0
С одной стороны, версии – это хорошо 
Но с другой, они автоматом не обновятся и придется мучиться с обновлением в будущем 
Точно нужны?

2022-07-18 18:16 UTC, dyakovri commented on calendar_backend/app.py
> +    global user_flow
Если там 

```python
@app.get(...)
def func():
  авторизуюсь на сервере
  генерю урл
  перехожу на урл
```

то лучше заменить это на 

```python
from functools import lru_cache

@lru_cache()  # Выполниться на каждый набор аргументов всего один раз и запишется в кэш
def auth(): ...  # авторизуюсь на сервере

def gen_url(): ...  # генерю урл

@app.get(...)
def func(): ...  # перехожу на урл
```

2022-08-07 21:28 UTC, closed without merging